package com.escalones.control12.vistas;

import com.escalones.control12.modelos.Articulo;
import com.escalones.control12.modelos.TipoAsistencia;
import com.escalones.control12.servicios.alumnos.AlumnoValidador;
import com.escalones.control12.servicios.articulos.ArticuloAccesoApi;
import com.escalones.control12.servicios.articulos.ArticuloAccionesFrame;
import com.escalones.control12.servicios.articulos.ArticuloValidador;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author xarxa
 */
public class ArticulosFrame extends javax.swing.JFrame {

    public static final int ACCIONALTA = 0;
    public static final int ACCIONMODIFICAR = 1;
    public static final int NINGUNARTICULOACTIVADO = -1;

    public int accionAltaModificar;
    public int idArticuloActual;

    public ArrayList<Articulo> articulos = new ArrayList<>();
    public ArrayList<TipoAsistencia> tiposAsistencia = new ArrayList<>();

    /**
     * Creates new form InicioFrame
     */
    public ArticulosFrame() {
        initComponents();
        idArticuloActual = NINGUNARTICULOACTIVADO;
        accionAltaModificar = ACCIONALTA;
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelBarraLateral = new javax.swing.JPanel();
        jPanelCabecera = new javax.swing.JPanel();
        jLabel12Escalones = new javax.swing.JLabel();
        jLabelAdministrador = new javax.swing.JLabel();
        jPanelZonaTabla = new javax.swing.JPanel();
        jPanelFormulario = new javax.swing.JPanel();
        jLabelAnadirArticulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTipoAsistencia = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelNumeroHoras = new javax.swing.JLabel();
        jTextFieldNumeroHoras = new javax.swing.JTextField();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabelIVA = new javax.swing.JLabel();
        jTextFieldIva = new javax.swing.JTextField();
        jComboBoxTipoAsistencia = new javax.swing.JComboBox<>();
        jPanelBotoneraFormulario = new javax.swing.JPanel();
        jButtonAnadirArticulo = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonInicio = new javax.swing.JButton();
        jPanelBusqueda = new javax.swing.JPanel();
        jButtonBuscarArticulo = new javax.swing.JButton();
        jTextFieldBuscarArticulo = new javax.swing.JTextField();
        jPanelTabla = new javax.swing.JPanel();
        jPanelBotonera = new javax.swing.JPanel();
        jButtonEditar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArticulos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jPanelBarraLateral.setBackground(new java.awt.Color(255, 153, 0));
        jPanelBarraLateral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelBarraLateralLayout = new javax.swing.GroupLayout(jPanelBarraLateral);
        jPanelBarraLateral.setLayout(jPanelBarraLateralLayout);
        jPanelBarraLateralLayout.setHorizontalGroup(
            jPanelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        jPanelBarraLateralLayout.setVerticalGroup(
            jPanelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelCabecera.setBackground(new java.awt.Color(255, 153, 51));
        jPanelCabecera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12Escalones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12Escalones.setText("CONTROL 12-ARTÍCULOS");

        jLabelAdministrador.setText("Administrador");

        javax.swing.GroupLayout jPanelCabeceraLayout = new javax.swing.GroupLayout(jPanelCabecera);
        jPanelCabecera.setLayout(jPanelCabeceraLayout);
        jPanelCabeceraLayout.setHorizontalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12Escalones, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCabeceraLayout.setVerticalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12Escalones, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addComponent(jLabelAdministrador)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelAnadirArticulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAnadirArticulo.setText("NUEVO ARTÍCULO");

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNombre.setText("NOMBRE");

        jLabelTipoAsistencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTipoAsistencia.setText("TIPO DE ASISTENCIA");

        jTextFieldNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNumeroHoras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNumeroHoras.setText("NÚMERO DE HORAS");

        jTextFieldNumeroHoras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldNumeroHoras.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPrecio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPrecio.setText("PRECIO");

        jTextFieldPrecio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldPrecio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelIVA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelIVA.setText("I.V.A");

        jTextFieldIva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIvaActionPerformed(evt);
            }
        });

        jComboBoxTipoAsistencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxTipoAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoAsistenciaActionPerformed(evt);
            }
        });

        jButtonAnadirArticulo.setBackground(new java.awt.Color(242, 183, 1));
        jButtonAnadirArticulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAnadirArticulo.setText("AÑADIR ARTÍCULO");
        jButtonAnadirArticulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonAnadirArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirArticuloActionPerformed(evt);
            }
        });

        jButtonLimpiar.setBackground(new java.awt.Color(255, 204, 102));
        jButtonLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLimpiar.setText("LIMPIAR FORMULARIO");
        jButtonLimpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonInicio.setText("INICIO");
        jButtonInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanelBotoneraFormularioLayout = new javax.swing.GroupLayout(jPanelBotoneraFormulario);
        jPanelBotoneraFormulario.setLayout(jPanelBotoneraFormularioLayout);
        jPanelBotoneraFormularioLayout.setHorizontalGroup(
            jPanelBotoneraFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoneraFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoneraFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAnadirArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoneraFormularioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBotoneraFormularioLayout.setVerticalGroup(
            jPanelBotoneraFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoneraFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAnadirArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFormularioLayout = new javax.swing.GroupLayout(jPanelFormulario);
        jPanelFormulario.setLayout(jPanelFormularioLayout);
        jPanelFormularioLayout.setHorizontalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumeroHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNumeroHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                    .addComponent(jLabelAnadirArticulo)
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipoAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIva, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTipoAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jPanelBotoneraFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jPanelFormularioLayout.setVerticalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAnadirArticulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelTipoAsistencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxTipoAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jTextFieldNombre))
                .addGap(23, 23, 23)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroHoras)
                    .addComponent(jLabelIVA)
                    .addComponent(jLabelPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNumeroHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addComponent(jPanelBotoneraFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelAnadirArticulo.getAccessibleContext().setAccessibleName("AÑADIR PROFESOR");

        jButtonBuscarArticulo.setBackground(new java.awt.Color(242, 183, 1));
        jButtonBuscarArticulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBuscarArticulo.setText("BUSCAR ARTÍCULO");
        jButtonBuscarArticulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonBuscarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarArticuloActionPerformed(evt);
            }
        });

        jTextFieldBuscarArticulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldBuscarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarArticuloActionPerformed(evt);
            }
        });
        jTextFieldBuscarArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarArticuloKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelBusquedaLayout = new javax.swing.GroupLayout(jPanelBusqueda);
        jPanelBusqueda.setLayout(jPanelBusquedaLayout);
        jPanelBusquedaLayout.setHorizontalGroup(
            jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldBuscarArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBusquedaLayout.setVerticalGroup(
            jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBuscarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBotonera.setBackground(new java.awt.Color(204, 204, 204));

        jButtonEditar.setBackground(new java.awt.Color(255, 204, 51));
        jButtonEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEditar.setText("EDITAR");
        jButtonEditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonBorrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBorrar.setText("BORRAR");
        jButtonBorrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoneraLayout = new javax.swing.GroupLayout(jPanelBotonera);
        jPanelBotonera.setLayout(jPanelBotoneraLayout);
        jPanelBotoneraLayout.setHorizontalGroup(
            jPanelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoneraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanelBotoneraLayout.setVerticalGroup(
            jPanelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoneraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableArticulos.setBackground(new java.awt.Color(236, 236, 236));
        jTableArticulos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTableArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Tipo de Asistencia", "Número de Horas", "Precio", "I.V.A."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableArticulos);

        javax.swing.GroupLayout jPanelTablaLayout = new javax.swing.GroupLayout(jPanelTabla);
        jPanelTabla.setLayout(jPanelTablaLayout);
        jPanelTablaLayout.setHorizontalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTablaLayout.setVerticalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addGroup(jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTablaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                    .addComponent(jPanelBotonera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelZonaTablaLayout = new javax.swing.GroupLayout(jPanelZonaTabla);
        jPanelZonaTabla.setLayout(jPanelZonaTablaLayout);
        jPanelZonaTablaLayout.setHorizontalGroup(
            jPanelZonaTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelZonaTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelZonaTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelZonaTablaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelZonaTablaLayout.setVerticalGroup(
            jPanelZonaTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelZonaTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanelBarraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelZonaTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBarraLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelZonaTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarArticuloActionPerformed

    private void jButtonAnadirArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirArticuloActionPerformed
        ArticuloValidador articuloValidador = new ArticuloValidador(this);
        if (!articuloValidador.validarFormularioArticulo()) {
            JOptionPane.showMessageDialog(null, articuloValidador.getErrores());
        } else {
        if (accionAltaModificar == ACCIONALTA) {
            ArticuloAccesoApi.nuevoArticulo(this);  // Método para añadir un nuevo artículo
           ArticuloAccionesFrame.borrarFormulario(this);
        } else if (accionAltaModificar == ACCIONMODIFICAR) {
            ArticuloAccesoApi.modificarArticulo(this);  // Método para modificar un artículo existente
        }
        }


    }//GEN-LAST:event_jButtonAnadirArticuloActionPerformed

    private void jButtonBuscarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarArticuloActionPerformed
         ArticuloAccionesFrame.filtrarTablaArticulos(this);
    }//GEN-LAST:event_jButtonBuscarArticuloActionPerformed

    private void jTextFieldBuscarArticuloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarArticuloKeyReleased
         ArticuloAccionesFrame.filtrarTablaArticulos(this);  // Método para filtrar la tabla de artículos
    }//GEN-LAST:event_jTextFieldBuscarArticuloKeyReleased

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // Acción para editar un artículo seleccionado en la tabla
        if (jTableArticulos.getSelectedRow() != -1) {
            idArticuloActual = (int) jTableArticulos.getValueAt(jTableArticulos.getSelectedRow(), 0);
            accionAltaModificar = ACCIONMODIFICAR;

            ArticuloAccionesFrame.modificarBotonesAltaModificar(this);  // Cambia los botones de alta/modificar según la acción actual

            ArticuloAccionesFrame.rellenarFormulario(this);  // Rellena el formulario con los datos del artículo seleccionado
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el artículo a editar");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

         ArticuloAccionesFrame.borrarFormulario(this);
        if (accionAltaModificar == ACCIONMODIFICAR) {
             ArticuloAccionesFrame.reiniciarAccionAlta(this);
        }
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        if (jTableArticulos.getSelectedRow() != -1) {
            idArticuloActual = (int) jTableArticulos.getValueAt(jTableArticulos.getSelectedRow(), 0);
            int respuesta = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de que desea eliminar este artículo?", 
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION);
            
            if (respuesta == JOptionPane.YES_OPTION) {
                ArticuloAccesoApi.eliminarArticulo(this);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el artículo a eliminar");
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jTextFieldIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIvaActionPerformed

    private void jComboBoxTipoAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoAsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArticulosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArticulosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArticulosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArticulosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArticulosFrame().setVisible(true);
            }
        });

    }

    public JTable getTablaArticulos() {
        return jTableArticulos;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAnadirArticulo;
    public javax.swing.JButton jButtonBorrar;
    public javax.swing.JButton jButtonBuscarArticulo;
    public javax.swing.JButton jButtonEditar;
    public javax.swing.JButton jButtonInicio;
    public javax.swing.JButton jButtonLimpiar;
    public javax.swing.JComboBox<TipoAsistencia> jComboBoxTipoAsistencia;
    private javax.swing.JLabel jLabel12Escalones;
    private javax.swing.JLabel jLabelAdministrador;
    private javax.swing.JLabel jLabelAnadirArticulo;
    private javax.swing.JLabel jLabelIVA;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumeroHoras;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTipoAsistencia;
    private javax.swing.JPanel jPanelBarraLateral;
    private javax.swing.JPanel jPanelBotonera;
    private javax.swing.JPanel jPanelBotoneraFormulario;
    private javax.swing.JPanel jPanelBusqueda;
    private javax.swing.JPanel jPanelCabecera;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JPanel jPanelZonaTabla;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableArticulos;
    public javax.swing.JTextField jTextFieldBuscarArticulo;
    public javax.swing.JTextField jTextFieldIva;
    public javax.swing.JTextField jTextFieldNombre;
    public javax.swing.JTextField jTextFieldNumeroHoras;
    public javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables


}
