package com.escalones.control12.vistas;

import com.escalones.control12.modelos.Alumno;
import com.escalones.control12.modelos.Articulo;
import com.escalones.control12.modelos.Pago;
import com.escalones.control12.modelos.PagoSimple;
import com.escalones.control12.servicios.pagos.PagoAccesoApi;
import com.escalones.control12.servicios.pagos.PagoAccionesFrame;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xarxa
 */
public class PagosFrame extends javax.swing.JFrame {

    public ArrayList<Articulo> articulos = new ArrayList<>();
    public ArrayList<Alumno> alumnos = new ArrayList<>();
    public ArrayList<PagoSimple> pagosSimples = new ArrayList<>();

    private PrevisualizacionTicketFrame ventanaPrevisualizacion;
    public Alumno alumnoSeleccionado; // Necesitas gestionar la selección del alumno
    public DefaultTableModel modeloLineaDetalle;

    public Alumno alumnoParaTicket;
    public ArrayList<PagoSimple> lineasParaTicket = new ArrayList<>();
    

    /**
     * Creates new form PagosFrame
     */
    public PagosFrame() {
        initComponents();
        // Establecer el color de fondo inicial del campo Entregado a rojo
        jTextFieldEntregado.setBackground(new java.awt.Color(255, 153, 153));
        ventanaPrevisualizacion = new PrevisualizacionTicketFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateFechaPago = new com.toedter.calendar.JDateChooser();
        jTextFieldBuscarAlumnoPagos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlumnosPagos = new javax.swing.JTable();
        jTextFieldBuscarArticuloPagos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableArticulosPagos = new javax.swing.JTable();
        jSpinnerUnidades = new javax.swing.JSpinner();
        jLabelUnidades = new javax.swing.JLabel();
        jButtonAnadirProducto = new javax.swing.JButton();
        jPanelCobro = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaObservaciones = new javax.swing.JTextArea();
        jLabelDescuento1 = new javax.swing.JLabel();
        jLabelEntregado = new javax.swing.JLabel();
        jLabelCambio = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jLabelCobro = new javax.swing.JLabel();
        jButtonAnularPago = new javax.swing.JButton();
        jButtonCobrar = new javax.swing.JButton();
        jPanelDescuento = new javax.swing.JPanel();
        jTextFieldDescuentoCantidad = new javax.swing.JTextField();
        jButtonAplicarDescuento = new javax.swing.JButton();
        jLabelCantidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDescuentoPorcentaje = new javax.swing.JTextField();
        jLabelDescuento = new javax.swing.JLabel();
        jTextFieldEntregado = new javax.swing.JTextField();
        jTextFieldCambio = new javax.swing.JTextField();
        jLabelFormaPago = new javax.swing.JLabel();
        jComboBoxFormaPago = new javax.swing.JComboBox<>();
        jButtonSeleccionarAlumno = new javax.swing.JButton();
        jLabelFecha = new javax.swing.JLabel();
        jLabelBuscarAlumno = new javax.swing.JLabel();
        jLabelBuscarProducto = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jSpinnerHora = new javax.swing.JSpinner();
        jSpinnerMinuto = new javax.swing.JSpinner();
        jLabelPuntosHora = new javax.swing.JLabel();
        jLabelMesPagado = new javax.swing.JLabel();
        jDateFechaMesPagado = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jPanelLateral = new javax.swing.JPanel();
        jPanelBarraLateral = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDatosPago = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableLineaDetalle = new javax.swing.JTable();
        jPanelCabecera = new javax.swing.JPanel();
        jLabel12Escalones1 = new javax.swing.JLabel();
        jLabelAdministrador1 = new javax.swing.JLabel();
        jPanelHistoricoPagos = new javax.swing.JPanel();
        jLabelHistoricoPagos = new javax.swing.JLabel();
        jPanelBusquedaPagos = new javax.swing.JPanel();
        jLabelBuscarPago = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableHistoricoPagos = new javax.swing.JTable();
        jPanelBotonera = new javax.swing.JPanel();
        jButtonEditar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonTicket = new javax.swing.JButton();
        jTextFieldBuscarAlumnoPagos1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldBuscarAlumnoPagos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldBuscarAlumnoPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarAlumnoPagosActionPerformed(evt);
            }
        });
        jTextFieldBuscarAlumnoPagos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarAlumnoPagosKeyReleased(evt);
            }
        });

        jTableAlumnosPagos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTableAlumnosPagos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTableAlumnosPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Apellidos", "Telefono", "Telefono 2", "e-mail", "Fecha Nacimiento", "Fecha Inscripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAlumnosPagos);

        jTextFieldBuscarArticuloPagos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldBuscarArticuloPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarArticuloPagosActionPerformed(evt);
            }
        });
        jTextFieldBuscarArticuloPagos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarArticuloPagosKeyReleased(evt);
            }
        });

        jTableArticulosPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Tipo de Asistencia", "Número de Horas", "Precio", "I.V.A."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableArticulosPagos);

        jSpinnerUnidades.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

        jLabelUnidades.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUnidades.setText("UNIDADES");

        jButtonAnadirProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAnadirProducto.setText("AÑADIR PRODUCTO");
        jButtonAnadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirProductoActionPerformed(evt);
            }
        });

        jTextAreaObservaciones.setColumns(20);
        jTextAreaObservaciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextAreaObservaciones.setRows(5);
        jScrollPane3.setViewportView(jTextAreaObservaciones);

        jLabelDescuento1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDescuento1.setText("OBSERVACIONES");

        jLabelEntregado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEntregado.setText("ENTREGADO");

        jLabelCambio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCambio.setText("CAMBIO");

        jTextFieldTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldTotal.setText("0");
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });

        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTotal.setText("TOTAL");

        jLabelCobro.setBackground(new java.awt.Color(255, 153, 0));
        jLabelCobro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCobro.setText("COBRO");
        jLabelCobro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonAnularPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAnularPago.setText("ANULAR");
        jButtonAnularPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnularPagoActionPerformed(evt);
            }
        });

        jButtonCobrar.setBackground(new java.awt.Color(255, 204, 102));
        jButtonCobrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCobrar.setText("COBRAR");
        jButtonCobrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCobrarActionPerformed(evt);
            }
        });

        jPanelDescuento.setBackground(new java.awt.Color(242, 182, 3));

        jTextFieldDescuentoCantidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldDescuentoCantidad.setText("0");
        jTextFieldDescuentoCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescuentoCantidadActionPerformed(evt);
            }
        });
        jTextFieldDescuentoCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDescuentoCantidadKeyReleased(evt);
            }
        });

        jButtonAplicarDescuento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAplicarDescuento.setText("APLICAR");
        jButtonAplicarDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarDescuentoActionPerformed(evt);
            }
        });

        jLabelCantidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCantidad.setText("CANTIDAD");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("PORCENTAJE");

        jTextFieldDescuentoPorcentaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldDescuentoPorcentaje.setText("0");
        jTextFieldDescuentoPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescuentoPorcentajeActionPerformed(evt);
            }
        });
        jTextFieldDescuentoPorcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDescuentoPorcentajeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelDescuentoLayout = new javax.swing.GroupLayout(jPanelDescuento);
        jPanelDescuento.setLayout(jPanelDescuentoLayout);
        jPanelDescuentoLayout.setHorizontalGroup(
            jPanelDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDescuentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDescuentoLayout.createSequentialGroup()
                        .addComponent(jLabelCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDescuentoLayout.createSequentialGroup()
                        .addComponent(jTextFieldDescuentoCantidad)
                        .addGap(27, 27, 27)))
                .addGroup(jPanelDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDescuentoPorcentaje))
                .addGap(18, 18, 18))
            .addGroup(jPanelDescuentoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonAplicarDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDescuentoLayout.setVerticalGroup(
            jPanelDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescuentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantidad)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescuentoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDescuentoPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAplicarDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabelDescuento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDescuento.setText("DESCUENTO");

        javax.swing.GroupLayout jPanelCobroLayout = new javax.swing.GroupLayout(jPanelCobro);
        jPanelCobro.setLayout(jPanelCobroLayout);
        jPanelCobroLayout.setHorizontalGroup(
            jPanelCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCobroLayout.createSequentialGroup()
                .addGroup(jPanelCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCobroLayout.createSequentialGroup()
                        .addGroup(jPanelCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCobroLayout.createSequentialGroup()
                                .addComponent(jLabelEntregado)
                                .addGap(41, 41, 41)
                                .addComponent(jLabelCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCobroLayout.createSequentialGroup()
                                .addGroup(jPanelCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelCobroLayout.createSequentialGroup()
                                        .addComponent(jLabelDescuento)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCobroLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonAnularPago, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(jButtonCobrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabelDescuento1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelCobro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCobroLayout.setVerticalGroup(
            jPanelCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCobroLayout.createSequentialGroup()
                .addComponent(jLabelCobro)
                .addGap(12, 12, 12)
                .addGroup(jPanelCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescuento1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTotal)
                        .addComponent(jLabelDescuento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCobroLayout.createSequentialGroup()
                        .addComponent(jPanelDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEntregado)
                            .addComponent(jLabelCambio)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCobroLayout.createSequentialGroup()
                        .addGroup(jPanelCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCobroLayout.createSequentialGroup()
                                .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCobroLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonAnularPago)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTextFieldEntregado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldEntregado.setText("0");
        jTextFieldEntregado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEntregadoKeyReleased(evt);
            }
        });

        jTextFieldCambio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldCambio.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAnadirProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCobro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldEntregado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelUnidades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonAnadirProducto))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCobro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEntregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabelFormaPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFormaPago.setText("FORMA DE PAGO");

        jComboBoxFormaPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Bizum", "Transferencia" }));

        jButtonSeleccionarAlumno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSeleccionarAlumno.setText("SELECCIONAR ALUMNO");
        jButtonSeleccionarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarAlumnoActionPerformed(evt);
            }
        });

        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFecha.setText("FECHA DE PAGO");

        jLabelBuscarAlumno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBuscarAlumno.setText("BUSCAR ALUMNO");

        jLabelBuscarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBuscarProducto.setText("BUSCAR PRODUCTO");

        jLabelHora.setText("HORA");

        jSpinnerHora.setModel(new javax.swing.SpinnerNumberModel(12, 0, 23, 1));

        jSpinnerMinuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabelPuntosHora.setText(":");

        jLabelMesPagado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMesPagado.setText("MES PAGADO");

        jDateFechaMesPagado.setDateFormatString("MMM y");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addComponent(jTextFieldBuscarArticuloPagos)
                    .addComponent(jTextFieldBuscarAlumnoPagos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFecha))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jSpinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelPuntosHora, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabelFormaPago)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabelMesPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jDateFechaMesPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButtonSeleccionarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jLabelFormaPago)
                    .addComponent(jLabelHora)
                    .addComponent(jLabelMesPagado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerMinuto)
                    .addComponent(jSpinnerHora)
                    .addComponent(jDateFechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPuntosHora)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jDateFechaMesPagado, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jComboBoxFormaPago))
                .addGap(18, 18, 18)
                .addComponent(jLabelBuscarAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarAlumnoPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSeleccionarAlumno)
                .addGap(18, 18, 18)
                .addComponent(jLabelBuscarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarArticuloPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanelBarraLateral.setBackground(new java.awt.Color(255, 153, 51));
        jPanelBarraLateral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelBarraLateralLayout = new javax.swing.GroupLayout(jPanelBarraLateral);
        jPanelBarraLateral.setLayout(jPanelBarraLateralLayout);
        jPanelBarraLateralLayout.setHorizontalGroup(
            jPanelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        jPanelBarraLateralLayout.setVerticalGroup(
            jPanelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLateralLayout = new javax.swing.GroupLayout(jPanelLateral);
        jPanelLateral.setLayout(jPanelLateralLayout);
        jPanelLateralLayout.setHorizontalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
            .addGroup(jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLateralLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanelBarraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelLateralLayout.setVerticalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
            .addGroup(jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLateralLayout.createSequentialGroup()
                    .addComponent(jPanelBarraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTableDatosPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Alumno", "Tipo de Pago", "Fecha", "Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableDatosPago);

        jTableLineaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Producto", "Unidades", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableLineaDetalle);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCabecera.setBackground(new java.awt.Color(255, 153, 51));
        jPanelCabecera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCabecera.setPreferredSize(new java.awt.Dimension(400, 42));

        jLabel12Escalones1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12Escalones1.setText("CONTROL12 - PAGOS");

        jLabelAdministrador1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAdministrador1.setText("Administrador");

        javax.swing.GroupLayout jPanelCabeceraLayout = new javax.swing.GroupLayout(jPanelCabecera);
        jPanelCabecera.setLayout(jPanelCabeceraLayout);
        jPanelCabeceraLayout.setHorizontalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addComponent(jLabel12Escalones1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1058, Short.MAX_VALUE)
                .addComponent(jLabelAdministrador1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCabeceraLayout.setVerticalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12Escalones1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAdministrador1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelHistoricoPagos.setBackground(new java.awt.Color(255, 153, 0));
        jLabelHistoricoPagos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelHistoricoPagos.setText("HISTÓRICO DE PAGOS");
        jLabelHistoricoPagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelBuscarPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBuscarPago.setText("BUSCAR FACTURA POR CLIENTE");

        jTableHistoricoPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NºFACTURA", "ALUMNO", "FECHA", "ARTÍCULOS", "IMPORTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTableHistoricoPagos);

        jButtonEditar.setText("EDITAR");

        jButtonBorrar.setText("BORRAR");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonImprimir.setText("IMPRIMIR");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        jButtonTicket.setText("TICKET");
        jButtonTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoneraLayout = new javax.swing.GroupLayout(jPanelBotonera);
        jPanelBotonera.setLayout(jPanelBotoneraLayout);
        jPanelBotoneraLayout.setHorizontalGroup(
            jPanelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoneraLayout.createSequentialGroup()
                .addComponent(jButtonEditar)
                .addGap(18, 18, 18)
                .addComponent(jButtonBorrar)
                .addGap(18, 18, 18)
                .addComponent(jButtonImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonTicket)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelBotoneraLayout.setVerticalGroup(
            jPanelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoneraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonImprimir)
                    .addComponent(jButtonTicket))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTextFieldBuscarAlumnoPagos1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextFieldBuscarAlumnoPagos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarAlumnoPagos1ActionPerformed(evt);
            }
        });
        jTextFieldBuscarAlumnoPagos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarAlumnoPagos1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelBusquedaPagosLayout = new javax.swing.GroupLayout(jPanelBusquedaPagos);
        jPanelBusquedaPagos.setLayout(jPanelBusquedaPagosLayout);
        jPanelBusquedaPagosLayout.setHorizontalGroup(
            jPanelBusquedaPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
            .addGroup(jPanelBusquedaPagosLayout.createSequentialGroup()
                .addComponent(jPanelBotonera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelBusquedaPagosLayout.createSequentialGroup()
                .addComponent(jLabelBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jTextFieldBuscarAlumnoPagos1)
        );
        jPanelBusquedaPagosLayout.setVerticalGroup(
            jPanelBusquedaPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaPagosLayout.createSequentialGroup()
                .addComponent(jLabelBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldBuscarAlumnoPagos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelHistoricoPagosLayout = new javax.swing.GroupLayout(jPanelHistoricoPagos);
        jPanelHistoricoPagos.setLayout(jPanelHistoricoPagosLayout);
        jPanelHistoricoPagosLayout.setHorizontalGroup(
            jPanelHistoricoPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBusquedaPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelHistoricoPagosLayout.createSequentialGroup()
                .addComponent(jLabelHistoricoPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHistoricoPagosLayout.setVerticalGroup(
            jPanelHistoricoPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoPagosLayout.createSequentialGroup()
                .addComponent(jLabelHistoricoPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBusquedaPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(367, 367, 367)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(464, 464, 464))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanelHistoricoPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 1398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelHistoricoPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeleccionarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarAlumnoActionPerformed
        // TODO add your handling code here:
        PagoAccionesFrame.anadirProductos(this);
        jButtonSeleccionarAlumno.setEnabled(false);
    }//GEN-LAST:event_jButtonSeleccionarAlumnoActionPerformed

    private void jButtonAnadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirProductoActionPerformed
        // TODO add your handling code here:
        PagoAccionesFrame.anadirUnProducto(this);
    }//GEN-LAST:event_jButtonAnadirProductoActionPerformed

    private void jButtonCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCobrarActionPerformed
        // TODO add your handling code here:

        //PagoValidador pagoValidador = new PagoValidador(this);
        // if (!pagoValidador.validarFormularioPago()) {
        // JOptionPane.showMessageDialog(null, pagoValidador.getErrores());
        //  } else {
        PagoAccesoApi.nuevoPago(this);
        JOptionPane.showMessageDialog(this, "Nuevo pago creado con éxito.");
        PagoAccionesFrame.actualizarTablaHistoricoPagos(this);
        jButtonSeleccionarAlumno.setEnabled(true);


    }//GEN-LAST:event_jButtonCobrarActionPerformed

    private void jButtonAnularPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnularPagoActionPerformed
        // TODO add your handling code here:
        PagoAccionesFrame.nuevoPago(this);
    }//GEN-LAST:event_jButtonAnularPagoActionPerformed

    private void jButtonAplicarDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarDescuentoActionPerformed
        // TODO add your handling code here:
        PagoAccionesFrame.calcularDescuento(this);
    }//GEN-LAST:event_jButtonAplicarDescuentoActionPerformed

    private void jTextFieldEntregadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEntregadoKeyReleased
        // TODO add your handling code here:
        PagoAccionesFrame.calcularCambio(this);
    }//GEN-LAST:event_jTextFieldEntregadoKeyReleased

    private void jTextFieldDescuentoCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescuentoCantidadKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescuentoCantidadKeyReleased

    private void jTextFieldDescuentoCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescuentoCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescuentoCantidadActionPerformed

    private void jTextFieldBuscarArticuloPagosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarArticuloPagosKeyReleased
        // ArticuloAccionesFrame.filtrarTablaArticulos(this);  // Método para filtrar la tabla de artículos
        PagoAccionesFrame.filtrarTablaArticulos(this);
    }//GEN-LAST:event_jTextFieldBuscarArticuloPagosKeyReleased

    private void jTextFieldBuscarArticuloPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarArticuloPagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarArticuloPagosActionPerformed

    private void jTextFieldBuscarAlumnoPagosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarAlumnoPagosKeyReleased
        // TODO add your handling code here:
        PagoAccionesFrame.filtrarTablaAlumnos(this);
    }//GEN-LAST:event_jTextFieldBuscarAlumnoPagosKeyReleased

    private void jTextFieldBuscarAlumnoPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarAlumnoPagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarAlumnoPagosActionPerformed

    private void jTextFieldDescuentoPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescuentoPorcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescuentoPorcentajeActionPerformed

    private void jTextFieldDescuentoPorcentajeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescuentoPorcentajeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescuentoPorcentajeKeyReleased

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jTextFieldBuscarAlumnoPagos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarAlumnoPagos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarAlumnoPagos1ActionPerformed

    private void jTextFieldBuscarAlumnoPagos1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarAlumnoPagos1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarAlumnoPagos1KeyReleased

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jButtonTicketActionPerformed(java.awt.event.ActionEvent evt) {
        // Validar alumno seleccionado
        if (alumnoParaTicket == null) {
            JOptionPane.showMessageDialog(this, 
                "Debe seleccionar un alumno", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        // Validar artículos
        if (jTableLineaDetalle.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, 
                "No hay productos añadidos", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        // Reconstruir lineasParaTicket si es necesario
        if (lineasParaTicket == null || lineasParaTicket.isEmpty()) {
            lineasParaTicket = new ArrayList<>();
            DefaultTableModel model = (DefaultTableModel) jTableLineaDetalle.getModel();
            
            for (int i = 0; i < model.getRowCount(); i++) {
                try {
                    PagoSimple linea = new PagoSimple();
                    
                    // Obtener datos de la tabla
                    String nombreArticulo = model.getValueAt(i, 0).toString();
                    int unidades = Integer.parseInt(model.getValueAt(i, 1).toString());
                    double precioUnitario = Double.parseDouble(
                        model.getValueAt(i, 2).toString().replace(",", "."));
                    
                    // Buscar artículo correspondiente
                    Articulo articulo = buscarArticuloPorNombre(nombreArticulo);
                    
                    // Configurar línea
                    linea.setArticulo(articulo);
                    linea.setUnidades(unidades);
                    linea.setPrecioUnitario(precioUnitario);
                    linea.setImporte(unidades * precioUnitario);
                    
                    lineasParaTicket.add(linea);
                    
                } catch (Exception e) {
                    System.err.println("Error procesando línea " + i + ": " + e.getMessage());
                }
            }
        }
    
        // Configurar previsualización
        try {
            ventanaPrevisualizacion.setAlumno(alumnoParaTicket);
            ventanaPrevisualizacion.setLineasDetalle(lineasParaTicket);
            ventanaPrevisualizacion.setTotal(Double.parseDouble(jTextFieldTotal.getText().replace(",", ".")));
            ventanaPrevisualizacion.setEntregado(Double.parseDouble(jTextFieldEntregado.getText().replace(",", ".")));
            ventanaPrevisualizacion.setCambio(Double.parseDouble(jTextFieldCambio.getText().replace(",", ".")));
            ventanaPrevisualizacion.setObservaciones(jTextAreaObservaciones.getText());
    
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            ventanaPrevisualizacion.setFecha(sdf.format(jDateFechaPago.getDate()));
            ventanaPrevisualizacion.setHora(jSpinnerHora.getValue() + ":" + 
                                          String.format("%02d", jSpinnerMinuto.getValue()));
            ventanaPrevisualizacion.setFormaPago(jComboBoxFormaPago.getSelectedItem().toString());
            
            ventanaPrevisualizacion.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al generar ticket: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Método auxiliar para buscar artículos
    private Articulo buscarArticuloPorNombre(String nombre) {
        for (Articulo articulo : articulos) {
            if (articulo.getNombre().equals(nombre)) {
                return articulo;
            }
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadirProducto;
    public javax.swing.JButton jButtonAnularPago;
    private javax.swing.JButton jButtonAplicarDescuento;
    private javax.swing.JButton jButtonBorrar;
    public javax.swing.JButton jButtonCobrar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonImprimir;
    public javax.swing.JButton jButtonSeleccionarAlumno;
    private javax.swing.JButton jButtonTicket;
    public javax.swing.JComboBox<String> jComboBoxFormaPago;
    public com.toedter.calendar.JDateChooser jDateFechaMesPagado;
    public com.toedter.calendar.JDateChooser jDateFechaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12Escalones1;
    private javax.swing.JLabel jLabelAdministrador1;
    public javax.swing.JLabel jLabelBuscarAlumno;
    private javax.swing.JLabel jLabelBuscarPago;
    private javax.swing.JLabel jLabelBuscarProducto;
    public javax.swing.JLabel jLabelCambio;
    private javax.swing.JLabel jLabelCantidad;
    public javax.swing.JLabel jLabelCobro;
    public javax.swing.JLabel jLabelDescuento;
    public javax.swing.JLabel jLabelDescuento1;
    public javax.swing.JLabel jLabelEntregado;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFormaPago;
    private javax.swing.JLabel jLabelHistoricoPagos;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelMesPagado;
    private javax.swing.JLabel jLabelPuntosHora;
    public javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelUnidades;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelBarraLateral;
    private javax.swing.JPanel jPanelBotonera;
    private javax.swing.JPanel jPanelBusquedaPagos;
    private javax.swing.JPanel jPanelCabecera;
    private javax.swing.JPanel jPanelCobro;
    private javax.swing.JPanel jPanelDescuento;
    private javax.swing.JPanel jPanelHistoricoPagos;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JSpinner jSpinnerHora;
    public javax.swing.JSpinner jSpinnerMinuto;
    public javax.swing.JSpinner jSpinnerUnidades;
    public javax.swing.JTable jTableAlumnosPagos;
    public javax.swing.JTable jTableArticulosPagos;
    public javax.swing.JTable jTableDatosPago;
    public javax.swing.JTable jTableHistoricoPagos;
    public javax.swing.JTable jTableLineaDetalle;
    public javax.swing.JTextArea jTextAreaObservaciones;
    public javax.swing.JTextField jTextFieldBuscarAlumnoPagos;
    public javax.swing.JTextField jTextFieldBuscarAlumnoPagos1;
    public javax.swing.JTextField jTextFieldBuscarArticuloPagos;
    public javax.swing.JTextField jTextFieldCambio;
    public javax.swing.JTextField jTextFieldDescuentoCantidad;
    public javax.swing.JTextField jTextFieldDescuentoPorcentaje;
    public javax.swing.JTextField jTextFieldEntregado;
    public javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
