package com.escalones.control12.vistas;

import com.escalones.control12.servicios.alumnos.AlumnoAccionesFrame;
import com.escalones.control12.servicios.articulos.ArticuloAccionesFrame;
import com.escalones.control12.servicios.pagos.PagoAccionesFrame;
import com.escalones.control12.servicios.profesores.ProfesorAccionesFrame;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import com.toedter.calendar.JDateChooser;
import static java.lang.System.exit;
import java.util.Date;

/**
 *
 * @author xarxa
 */
public class PantallaInicio extends javax.swing.JFrame {

    AlumnoFrame ventanaAlumno;
    ProfesorFrame ventanaProfesor;
    ArticulosFrame ventanaArticulos;
    PagosFrame ventanaPagos;
    /**
     * Creates new form PantallaInicio
     */
    public PantallaInicio() {
        initComponents();
        ImageIcon iconoAlumno = new ImageIcon(PantallaInicio.class.getResource("/com/escalones/control12/images/alumno.png"));
        jButtonAlumno.setIcon(iconoAlumno);
        ImageIcon iconoProfesor = new ImageIcon(PantallaInicio.class.getResource("/com/escalones/control12/images/profesor.png"));
        jButtonProfesor.setIcon(iconoProfesor);
        ImageIcon iconoArticulo = new ImageIcon(PantallaInicio.class.getResource("/com/escalones/control12/images/articulos.png"));
        jButtonArticulo.setIcon(iconoArticulo);
        ImageIcon iconoPago = new ImageIcon(PantallaInicio.class.getResource("/com/escalones/control12/images/pagos.png"));
        jButtonPago.setIcon(iconoPago);
        
        ventanaAlumno = new AlumnoFrame(this);
        AlumnoAccionesFrame.actualizarTablaAlumnos(ventanaAlumno);
        ventanaAlumno.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ventanaProfesor = new ProfesorFrame();
        ProfesorAccionesFrame.actualizarTablaProfesores(ventanaProfesor);
        ventanaProfesor.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ventanaArticulos = new ArticulosFrame();
        ArticuloAccionesFrame.actualizarTablaArticulos(ventanaArticulos);
        ArticuloAccionesFrame.actualizarTiposAsistencia(ventanaArticulos);
        ventanaArticulos.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ventanaPagos = new PagosFrame();
       PagoAccionesFrame.actualizarTablaHistoricoPagos(ventanaPagos);
        // Inicializar JDateChooser con la fecha actual
        
        ventanaPagos.jDateFechaPago.setDate(new Date());
        PagoAccionesFrame.actualizarTablaAlumnos(ventanaPagos);
        PagoAccionesFrame.actualizarTablaArticulos(ventanaPagos);
        PagoAccionesFrame.actualizarSpinnerHora(ventanaPagos);
        ventanaPagos.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        
        
    }
    
    public void actualizarElementos(){
        AlumnoAccionesFrame.actualizarTablaAlumnos(ventanaAlumno);
        ProfesorAccionesFrame.actualizarTablaProfesores(ventanaProfesor);
        ArticuloAccionesFrame.actualizarTablaArticulos(ventanaArticulos);
        PagoAccionesFrame.actualizarTablaAlumnos(ventanaPagos);
        PagoAccionesFrame.actualizarTablaArticulos(ventanaPagos);
        PagoAccionesFrame.actualizarSpinnerHora(ventanaPagos);
        PagoAccionesFrame.actualizarTablaHistoricoPagos(ventanaPagos);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonProfesor = new javax.swing.JButton();
        jButtonArticulo = new javax.swing.JButton();
        jButtonPago = new javax.swing.JButton();
        jButtonAlumno = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(254, 94, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("CONTROL12");

        jButtonProfesor.setBackground(new java.awt.Color(254, 94, 0));
        jButtonProfesor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonProfesor.setText("PROFESORES");
        jButtonProfesor.setBorder(null);
        jButtonProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProfesorActionPerformed(evt);
            }
        });

        jButtonArticulo.setBackground(new java.awt.Color(254, 94, 0));
        jButtonArticulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonArticulo.setText("ARTÍCULOS");
        jButtonArticulo.setBorder(null);
        jButtonArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArticuloActionPerformed(evt);
            }
        });

        jButtonPago.setBackground(new java.awt.Color(254, 94, 0));
        jButtonPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPago.setText("PAGOS");
        jButtonPago.setBorder(null);
        jButtonPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagoActionPerformed(evt);
            }
        });

        jButtonAlumno.setBackground(new java.awt.Color(254, 94, 0));
        jButtonAlumno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAlumno.setText("ALUMNOS");
        jButtonAlumno.setBorder(null);
        jButtonAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlumnoActionPerformed(evt);
            }
        });

        jButtonSalir.setBackground(new java.awt.Color(254, 94, 0));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logotipo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonPago, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(jButtonProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(472, 472, 472)
                                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabelLogo)))
                .addContainerGap())
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelLogo)))
                .addGap(50, 50, 50)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPago, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlumnoActionPerformed
        // TODO add your handling code here:
        
        ventanaAlumno.setVisible(true);
        
    }//GEN-LAST:event_jButtonAlumnoActionPerformed

    private void jButtonProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProfesorActionPerformed
        // TODO add your handling code here:
        
        ventanaProfesor.setVisible(true);
        
    }//GEN-LAST:event_jButtonProfesorActionPerformed

    private void jButtonArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArticuloActionPerformed
        // TODO add your handling code here:
        
        ventanaArticulos.setVisible(true);
        
    }//GEN-LAST:event_jButtonArticuloActionPerformed

    private void jButtonPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagoActionPerformed
        // TODO add your handling code here:
        ventanaPagos.setVisible(true);
    }//GEN-LAST:event_jButtonPagoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        int opcion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Está seguro que desea salir?", "Confirmar salida", javax.swing.JOptionPane.YES_NO_OPTION);
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            exit(0);
        }
        
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    int opcion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Está seguro que desea salir?", "Confirmar salida", javax.swing.JOptionPane.YES_NO_OPTION);
    if (opcion == javax.swing.JOptionPane.YES_OPTION) {
        exit(0);
    }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlumno;
    private javax.swing.JButton jButtonArticulo;
    private javax.swing.JButton jButtonPago;
    private javax.swing.JButton jButtonProfesor;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
